FROM swift:3.1

WORKDIR /code
ARG BUILD_CONFIGURATION=debug

COPY Package.swift Package.pins /code/
RUN swift build -c $BUILD_CONFIGURATION || true

COPY ./Sources /code/Sources
RUN swift build -c $BUILD_CONFIGURATION

EXPOSE 8000
ENV BUILD_CONFIGURATION $BUILD_CONFIGURATION
CMD .build/$BUILD_CONFIGURATION/App
